# Generated by Django 4.1.4 on 2023-01-18 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='operator_code',
            field=models.CharField(editable=False, max_length=11, validators=[django.core.validators.RegexValidator(message="Operator code must be entered in the format: '999'", regex='^\\d{3}$')], verbose_name='Код оператора'),
        ),
    ]
