# Generated by Django 4.1.4 on 2023-01-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='operator_code',
            field=models.CharField(editable=False, max_length=3, verbose_name='Код оператора'),
        ),
    ]
