# Generated by Django 4.1.4 on 2023-01-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_client_operator_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='operator_code',
        ),
    ]
